### ISSUE TITLE
Change the internal port 8000 of rsstranslator

### ISSUE THREAD

**Issue by DrakeDrole** [rss-translator/RSS-Translator#105]
### 概述 | Summary

I'm using Docker Compose, and I'd like to change the internal port 8000 of rsstranslator. Is there an environment variable to change the port?

**Comment by versun** [comment]
If you want to change the port that is exposed to your host (the external port), you can modify the ports section in your docker-compose.yml file. For example, to map host port 9000 to container port 8000:

```
rsstranslator:
    image: rsstranslator/rsstranslator
    ports:
      - "9000:8000"
```
This will make the application accessible on port 9000 of your host, but it will still run on port 8000 inside the container
